name: Run tests

on:
  - pull_request
  - push

jobs:
  ci:
    uses: houseabsolute/workflow-perl-dzil-ci/.github/workflows/ci.yml@v0
    with:
      dist: Code-TidyAll
      min-perl: "5.12.0" 
      ref: v0
      apt-packages-for-author-tests: |
        aspell
        aspell-en
        iamerican
        ispell
        nodejs
        php-cli
        php-xml
        subversion
